names_string = input("Enter the names for all the students separated by white space:")
name_list = names_string.split()
name_list = sorted(name_list)
name_list = list(dict.fromkeys(name_list))
print("The sorted list and duplicates removed:",name_list)
total_number=len(name_list)
print("The total number of names:",total_number)